project:
  output-dir: _site
  type: book

book:
  title: "qmd"
  author: 
  - Lucien Deforge
  - Luca Pallagi
  - Jakub Pilecki
  date: "24.10.2025"
  chapters:
    - index.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt